version: '3'

services: 
    backend:
        container_name: backend
        build: 
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        ports:
            - 5000:5000
        volumes: 
            - ./backend/app:/app
    
    frontend:
        container_name: frontend
        tty: true
        build:
            context:  ./frontend
            dockerfile: Dockerfile
        restart: always
        ports: 
            - 80:3000
        volumes: 
            - ./frontend/src:/app/src/
            - ./frontend/public:/app/public/