version: '3'

services: 
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile.prod
        ports:
            - 5000:5000
    
    frontend:
        build:
            context:  ./frontend
            dockerfile: Dockerfile.prod
        ports: 
            - 80:80