FROM python:3.7.9-buster

WORKDIR /app

COPY ./gunicorn_conf.py gunicorn_conf.py

RUN pip install --upgrade pip
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./app/ /app/

ENTRYPOINT ["gunicorn","--config","gunicorn_conf.py","main:app"]